apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
  namespace: observability
data:
  opensearch.yml: |
    cluster.name: auto-inspection-opensearch
    node.name: opensearch-0
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300
    discovery.type: single-node
    path.repo: ["/usr/share/opensearch/data/snapshots"]
    plugins.security.disabled: true
    cluster.routing.allocation.disk.threshold_enabled: true
    cluster.routing.allocation.disk.watermark.low: "85%"
    cluster.routing.allocation.disk.watermark.high: "90%"
    cluster.routing.allocation.disk.watermark.flood_stage: "95%"
    cluster.info.update.interval: 1m
    action.auto_create_index: true
