apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-bootstrap-application.yaml
  - argocd-bootstrap-project.yaml
  - argocd-core-application.yaml
  - argocd-core-project.yaml
  - monitoring-project.yaml
  - opspilot-core-application.yaml
  - opspilot-prometheus-application.yaml
