apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla-config
  namespace: observability
  labels:
    app.kubernetes.io/name: beyla
    app.kubernetes.io/part-of: auto-inspection
data:
  beyla-config.yml: |
    attributes:
      kubernetes:
        enable: true
    grafana:
      otlp:
        submit: ["metrics", "traces"]
    discovery:
      instrument:
        - k8s_namespace: "*"
          exe_path: "*"
          containers_only: true
      exclude_instrument:
        - k8s_namespace: "kube-system"
        - k8s_namespace: "kube-public"
        - k8s_namespace: "kube-node-lease"
        - k8s_namespace: "argocd"
        - k8s_namespace: "observability"
    metrics:
      features:
        - application
        - application_span
        - application_service_graph
