apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap-logs.yaml
- daemonset-logs.yaml
- configmap-events.yaml
- deployment-events.yaml

