FROM docker-hub.tpo.xzoa.com/python:3.12-slim

RUN set -ex \
    && python -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    && python -m pip install --upgrade pip \
    && python -m pip install --default-timeout=300 --no-cache-dir \
        fastapi \
        "uvicorn[standard]" \
        kubernetes \
        pydantic
