apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-core
  namespace: observability
spec:
  project: argocd-core
  source:
    repoURL: 'http://192.168.48.206:8929/platform/gitops-manifests.git'
    targetRevision: main
    path: clusters/test/argocd-core
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
