apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: observability
spec:
  project: observability
  source:
    repoURL: 'http://192.168.48.206:8929/platform/gitops-manifests.git'
    targetRevision: main
    path: clusters/test/observability
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
