apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: observability
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-206-observability-minio-static
  volumeName: minio-nfs-pv-206
