alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: true
  image:
    registry: k8s.m.daocloud.io
    repository: kube-state-metrics/kube-state-metrics
    tag: v2.18.0
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus-node-exporter:
  enabled: true
  resources: {}

server:
  nodeSelector:
    kubernetes.io/hostname: xzyc115-19
  retention: "7d"
  storagePath: /prometheus-data
  strategy:
    type: Recreate
  resources:
    requests:
      cpu: 250m
      memory: 768Mi
    limits:
      cpu: "1"
      memory: 2Gi
  persistentVolume:
    enabled: false
  extraVolumes:
    - name: prometheus-data
      hostPath:
        path: /data/auto-inspection/prometheus
        type: DirectoryOrCreate
  extraVolumeMounts:
    - name: prometheus-data
      mountPath: /prometheus-data
  service:
    enabled: true
    type: NodePort
    servicePort: 9090
    nodePort: 32092

