apiVersion: opspilot.io/v1
kind: Datasource
metadata:
  name: node200-logs
spec:
  kind: elasticsearch
  environment: test
  region: chengdu-inner
  url: http://elasticsearch.logging.svc.cluster.local:9200
  indexes:
    apisix: apisix-*
    app_default:
      - opspilot-k8s-*
  fields:
    time: "@timestamp"
    host: host_02
    uri: uri
    status: status
    request_time: request_time
    upstream_addr: upstream_addr
    service_uri: msg
