apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-data
  namespace: observability
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-206-observability-opensearch-static
  volumeName: opensearch-nfs-pv-206

