apiVersion: v1
kind: Service
metadata:
  name: opensearch-headless
  namespace: observability
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: opensearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  - name: transport
    port: 9300
    targetPort: 9300
  - name: metrics
    port: 9600
    targetPort: 9600

