apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-inspection-rca-read
subjects:
- kind: ServiceAccount
  name: auto-inspection-rca
  namespace: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auto-inspection-rca-read
