apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: observability
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/part-of: auto-inspection
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: falco
  template:
    metadata:
      labels:
        app.kubernetes.io/name: falco
        app.kubernetes.io/part-of: auto-inspection
    spec:
      serviceAccountName: falco
      containers:
      - name: falco
        image: docker-hub.tpo.xzoa.com/auto-inspection/falco:0.43.1
        imagePullPolicy: IfNotPresent
        args:
        - /usr/bin/falco
        env:
        - name: HOST_ROOT
          value: /host
        - name: FALCO_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: FALCO_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        ports:
        - name: web
          containerPort: 8765
        startupProbe:
          httpGet:
            path: /healthz
            port: 8765
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 24
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8765
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8765
          periodSeconds: 15
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 1Gi
        volumeMounts:
        - name: containerd-socket
          mountPath: /host/run/containerd/containerd.sock
        - name: host-containerd-socket
          mountPath: /host/run/host-containerd/containerd.sock
        - name: proc-fs
          mountPath: /host/proc
        - name: etc-fs
          mountPath: /host/etc
          readOnly: true
        - name: sys-kernel
          mountPath: /sys/kernel
          readOnly: true
        - name: root-falco-fs
          mountPath: /root/.falco
        - name: config
          mountPath: /etc/falco/falco.yaml
          subPath: falco.yaml
      tolerations:
      - operator: Exists
      volumes:
      - name: containerd-socket
        hostPath:
          path: /run/containerd/containerd.sock
      - name: host-containerd-socket
        hostPath:
          path: /run/containerd/containerd.sock
      - name: proc-fs
        hostPath:
          path: /proc
      - name: etc-fs
        hostPath:
          path: /etc
      - name: sys-kernel
        hostPath:
          path: /sys/kernel
      - name: root-falco-fs
        emptyDir: {}
      - name: config
        configMap:
          name: falco
          items:
          - key: falco.yaml
            path: falco.yaml
