apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-pyroscope-ebpf
  namespace: observability
  labels:
    app.kubernetes.io/name: alloy-pyroscope-ebpf
    app.kubernetes.io/part-of: auto-inspection
