apiVersion: v1
kind: Service
metadata:
  name: pyroscope
  namespace: observability
  labels:
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/part-of: auto-inspection
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: pyroscope
  ports:
  - name: http
    port: 4040
    targetPort: 4040
    nodePort: 32095
