apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-inspection-rca-source
  namespace: observability
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-206-observability-rca-static
  volumeName: auto-inspection-rca-source-pv-206
