services:
  node-exporter:
    image: docker-hub.tpo.xzoa.com/opspilot/node-exporter:v1.11.1
    container_name: node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    command:
      - --path.rootfs=/host
      - --web.listen-address=:9100
    volumes:
      - /:/host:ro,rslave
