services:
  prometheus:
    image: docker-hub.tpo.xzoa.com/opspilot/prometheus:v3.11.0
    container_name: prometheus
    restart: unless-stopped
    network_mode: host
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --web.listen-address=0.0.0.0:9090
      - --web.enable-lifecycle
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /opt/prometheus/data:/prometheus
