apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pyroscope-deployment.yaml
- pyroscope-service.yaml
- alloy-serviceaccount.yaml
- alloy-clusterrole.yaml
- alloy-clusterrolebinding.yaml
- alloy-configmap.yaml
- alloy-daemonset.yaml

