apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beyla-observability
rules:
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["pods", "services", "nodes", "namespaces"]
  verbs: ["list", "watch"]
